#!/bin/bash



sxhkd -c /home/phil/.config/bspwm/sxhkdrc &
xrandr -s 1920x1080
#blueman-applet &
#setxkbmap gb &
#volumeicon &
lxpolkit &
picom &
nitrogen --restore &
nm-applet &

parcellite &
#clementine &
lxappearance &

$HOME/.config/polybar-bspwm/launch.sh &
#feh --bg-scale  ~/Pictures/wallpapers/bspwm.jpg &
################################Together####
####~/.config/bspwm/sta &
#~/.local/bin/succade &
############################################

######PATH not set yet############
#~/.config/bspwm/launch.sh NOT USED





bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

bsp config presel_feedback_color "#ffffff"

bspc config normal_border_color "#454849"



bspc config focused_border_color "#3399ff"


bspc config top_padding 48

bspc config focus_follows_pointer true

#####bspc config initial_polarity second_child
#####bspc config automatic_scheme longest_side

##bspc config automatic_scheme spiral
##bspc config automatic_scheme longest_side
##bspc config initial_polarity second_child

#bspc config history_aware_focus	false
bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config center_pseudo_tiled true
 
# Automatic Splitting Settings
bspc config automatic_scheme	spiral
bspc config initial_polarity	first_child

bspc config pointer_modifier mod1 #Alt + right click modifies windows



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1' follow=on
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a firefox desktop=^2
#bspc rule -a Geany desktop=^3
bspc rule -a Xfce4-terminal state=floating

#clementine 
